### ISSUE TITLE
How to install another model other than the original v1-5?

### ISSUE THREAD

**Issue by baclazhan-ctrl** [CS1o/Stable-Diffusion-Info#11]
Hello, you helped me make stable diffusion work on my rx570

So it started working, but I can’t figure out how to change the originally installed model v1-5 to mistoonAnime_ponyAlpha, which I downloaded from civitai? 

I tried just putting it in the models\stable-siffusion folder,
but the program again gives a connection error, here in this folder there is a text file where I need to write some checkpoints, where to get them from?
please help
![изображение_2024-11-19_155521749](https://github.com/user-attachments/assets/f9d639af-c7a8-40bb-b9cc-a7dc7983fec9)

**Comment by CS1o** [comment]
Hey, you have to enable the FP8 mode for Sdxl in the Webui Settings.
Pony models are SDXL based.
Also you need to have 16GB RAM + a Pagefile on an SSD that is set to 16000min and 24000max.

If that wont help you can try install the Forge Webui with Zluda. It has some more optimisations.

**Comment by baclazhan-ctrl** [comment]
everything works!)
and the last question, I downloaded everything from the same site Lora, everything seems to be correct for my Pony model, I placed it in the models\Lora folder, but now I again have a connection error at startup, what is this causing?

**Comment by baclazhan-ctrl** [comment]
Oh no..
it stopped working completely, again the error always occurs on startup, but I was just happy

**Comment by baclazhan-ctrl** [comment]
```
venv "E:\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
WARNING: ZLUDA works best with SD.Next. Please consider migrating to SD.Next.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.10.1-amd-17-g745b20b7
Commit hash: 745b20b7c69a1fa10ee789b3981484389ac80aef
ROCm: agents=['gfx803']
ROCm: version=5.7, using agent gfx803
ZLUDA support: experimental
Using ZLUDA in E:\stable-diffusion-webui-directml\.zluda
Skipping onnxruntime installation.
You are up to date with the most recent release.
E:\stable-diffusion-webui-directml\venv\lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
E:\stable-diffusion-webui-directml\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Launching Web UI with arguments: --use-zluda --update-check --skip-ort --medvram
Loading weights [93f242d1d7] from E:\stable-diffusion-webui-directml\models\Stable-diffusion\mistoonAnime_ponyAlpha.safetensors
Creating model from config: E:\stable-diffusion-webui-directml\repositories\generative-models\configs\inference\sd_xl_base.yaml
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 22.4s (prepare environment: 27.5s, initialize shared: 3.8s, other imports: 0.7s, load scripts: 1.1s, create ui: 1.1s, gradio launch: 0.9s).
creating model quickly: OSError
Traceback (most recent call last):
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\utils\_http.py", line 406, in hf_raise_for_status
    response.raise_for_status()
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/None/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\utils\hub.py", line 403, in cached_file
    resolved_file = hf_hub_download(
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\file_download.py", line 862, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\file_download.py", line 969, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\file_download.py", line 1484, in _raise_on_head_call_error
    raise head_call_error
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\file_download.py", line 1376, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\file_download.py", line 1296, in get_hf_file_metadata
    r = _request_wrapper(
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\file_download.py", line 277, in _request_wrapper
    response = _request_wrapper(
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\file_download.py", line 301, in _request_wrapper
    hf_raise_for_status(response)
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\utils\_http.py", line 454, in hf_raise_for_status
    raise _format(RepositoryNotFoundError, message, response) from e
huggingface_hub.errors.RepositoryNotFoundError: 404 Client Error. (Request ID: Root=1-673cd139-3fb366e00ec00aa40fa24e44;40fb613d-eb4d-43d0-b781-d0d10a74b366)

Repository Not Found for url: https://huggingface.co/None/resolve/main/config.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\svbac\AppData\Local\Programs\Python\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\svbac\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\svbac\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "E:\stable-diffusion-webui-directml\modules\initialize.py", line 149, in load_model
    shared.sd_model  # noqa: B018
  File "E:\stable-diffusion-webui-directml\modules\shared_items.py", line 190, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "E:\stable-diffusion-webui-directml\modules\sd_models.py", line 693, in get_sd_model
    load_model()
  File "E:\stable-diffusion-webui-directml\modules\sd_models.py", line 831, in load_model
    sd_model = instantiate_from_config(sd_config.model, state_dict)
  File "E:\stable-diffusion-webui-directml\modules\sd_models.py", line 775, in instantiate_from_config
    return constructor(**params)
  File "E:\stable-diffusion-webui-directml\repositories\generative-models\sgm\models\diffusion.py", line 61, in __init__
    self.conditioner = instantiate_from_config(
  File "E:\stable-diffusion-webui-directml\repositories\generative-models\sgm\util.py", line 175, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "E:\stable-diffusion-webui-directml\repositories\generative-models\sgm\modules\encoders\modules.py", line 88, in __init__
    embedder = instantiate_from_config(embconfig)
  File "E:\stable-diffusion-webui-directml\repositories\generative-models\sgm\util.py", line 175, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "E:\stable-diffusion-webui-directml\repositories\generative-models\sgm\modules\encoders\modules.py", line 361, in __init__
    self.transformer = CLIPTextModel.from_pretrained(version)
  File "E:\stable-diffusion-webui-directml\modules\sd_disable_initialization.py", line 68, in CLIPTextModel_from_pretrained
    res = self.CLIPTextModel_from_pretrained(None, *model_args, config=pretrained_model_name_or_path, state_dict={}, **kwargs)
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\modeling_utils.py", line 3506, in from_pretrained
    resolved_config_file = cached_file(
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\utils\hub.py", line 426, in cached_file
    raise EnvironmentError(
OSError: None is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`

Failed to create model quickly; will retry using slow method.
Applying attention optimization: Doggettx... done.
Для продолжения нажмите любую клавишу . . .
```

**Comment by CS1o** [comment]
Okay then revert the changes (disable FP8 Mode again). To do that you need to remove the pony sdxl models from the model/stable-diffusion folder and then relaunch with an 1.5 model.
Then you can disable the FP8 Mode in Settings and hit Apply.
Then you can relaunch and add the pony model back in.

**Comment by baclazhan-ctrl** [comment]
Well, I did that and the program actually started to turn on
I changed the swap file on the disk on which the program folder is located (I have it on an SSD, I have an HHD disk with the system)

For some reason, when I add Lora, it stops working, well, I’ll try, following your advice, download Forge Webui
:)

**Comment by CS1o** [comment]
Ohh, yea only enable the Pagefile for the SSD and disable it for the HDD. And maybe consider installing your System onto the SSD too in the Future.

**Comment by baclazhan-ctrl** [comment]
YAY IT WORKED!!
IT'S FINALLY WORKING

THANK YOU SO MUCH DUDE, I DON'T EVEN KNOW HOW TO DESCRIBE HOW GRATEFUL I AM FOR YOUR HELP!

I am now the happiest person :)
![00018-919001549](https://github.com/user-attachments/assets/cedba0d1-c058-4b33-a457-dee9e5df3f18)

**Comment by CS1o** [comment]
Nice! No problem :) Have Fun!
