### ISSUE TITLE
i tried forge ui with zluda but it just says no CUDA gpus avalaible

### ISSUE THREAD

**Issue by picarica** [CS1o/Stable-Diffusion-Info#9]
```
venv "C:\stable-diffusion-webui-amdgpu-forge\venv\Scripts\Python.exe"
WARNING: ZLUDA works best with SD.Next. Please consider migrating to SD.Next.
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: f2.0.1v1.10.1-1.10.1
Commit hash: 50648cda2cc8ef0a63b7d727be86cdb0c6fca0ec
ROCm: no agent was found
ROCm: version=6.1
ZLUDA support: experimental
Using ZLUDA in C:\ZLUDA
Installing requirements
Launching Web UI with arguments: --zluda --use-zluda
Traceback (most recent call last):
  File "C:\stable-diffusion-webui-amdgpu-forge\launch.py", line 54, in <module>
    main()
  File "C:\stable-diffusion-webui-amdgpu-forge\launch.py", line 50, in main
    start()
  File "C:\stable-diffusion-webui-amdgpu-forge\modules\launch_utils.py", line 682, in start
    import webui
  File "C:\stable-diffusion-webui-amdgpu-forge\webui.py", line 17, in <module>
    initialize_forge()
  File "C:\stable-diffusion-webui-amdgpu-forge\modules_forge\initialization.py", line 58, in initialize_forge
    from backend import memory_management
  File "C:\stable-diffusion-webui-amdgpu-forge\backend\memory_management.py", line 133, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "C:\stable-diffusion-webui-amdgpu-forge\backend\memory_management.py", line 100, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "C:\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\cuda\__init__.py", line 778, in current_device
    _lazy_init()
  File "C:\stable-diffusion-webui-amdgpu-forge\venv\lib\site-packages\torch\cuda\__init__.py", line 293, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
Press any key to continue . . .
```

i downloadd everrythingi have hip library zluda in C:\ with correct arch for my GPU why is it not working?

**Comment by CS1o** [comment]
Hey, the log says no ROCm Agent found. Meaning ROCm is correctly installed but the GPU hasnt been recognized by it.
Whats your GPU?
Make sure you replaced the rocm library files with the custom ones made for your GPU and then restart the PC.
Then delete the venv folder and the .zluda folder in stable-diffusioin-webui-forge-amdgpu.
Then relaunch the webui-user.bat

**Comment by CS1o** [comment]
Closed as you switched to Linux and moved the conversation to:
https://github.com/lshqqytiger/stable-diffusion-webui-amdgpu/issues/552
RX570 and RX580 work only with HIP SDK 5.7
